[workspace]
resolver = "3"
members = ["nrf-hal","rad", "sim"]

[workspace.dependencies]
anyhow = "1"
cortex-m = {version = "0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.5"
defmt = "1"
mantra-macros = { path = "/Users/manuelhatzl/Documents/Projects/mantra/mantra/langs/rust/mantra-macros" }
