[package]
name = "rad"
version = "0.1.0"
edition = "2021"

[dependencies]
nrf-hal = { path = "../nrf-hal", optional = true }
cortex-m-rt.workspace = true
defmt = { workspace = true, optional = true }
mantra-macros.workspace = true

[dev-dependencies]
mockall = "0.15.0"
mockall_double = "0.3.1"

[features]
default = ["hw", "hw-testing"]
hw = ["nrf-hal", "defmt"]
hw-testing = ["hw"]
